%import common.DIGIT
%import common.WS_INLINE
%import common.NEWLINE
%import common.SIGNED_INT -> NUMBER
ID_START: /[\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}_]+/ -> idstart

ID_CONTINUE: ID_START | /[\p{Mn}\p{Mc}\p{Nd}\p{Pc}·]+/ -> idcontinue

Prog: Command+ -> cmds

Command: "print" _WS text -> print
	| "ask" _WS text -> ask
	| "echo" _WS text -> echo
	| "forward" _WS number -> forward
	| "turn" _WS text -> turn
	| text -> invalid_space
	| textwithoutspaces _WS text? -> invalid

_WS: " "* -> _WS
