STRING: /"[^"]"/ -> string

ID: /[a-zA-Z][a-zA-Z0-9]*/ -> id

form: "form"  ID  question* -> form

type: "boolean" -> bool

bool: "true" -> true
	| "false" -> false

question: "ask"  STRING  "into"  ID  ":"  type -> question
	| "if"  "("  or_expr  ")"  question -> ifThen

or_expr: and_expr  "||"  or_expr -> or
	| and_expr -> and

and_expr: primary  "&&"  and_expr -> and
	| primary -> prim

primary: ID -> ref
	| bool -> boolean
